global:
  # >>> Execute the following command to receive the domain:
  # $ kubectl get gateway -n kyma-system kyma-gateway -o jsonpath='{.spec.servers[0].hosts[0]}'
  # Remove the leading "*."
  domain: null
  imagePullSecret:
    name: container-registry
hana_deployer:
  image:
    # >>> Replace <your-container-registry> with your container registry
    repository: <your-container-registry>/sflight-hana-deployer
    tag: latest
  bindings:
    hana:
      fromSecret: sflight-db
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
destination:
  serviceOfferingName: destination
  servicePlanName: lite
  parameters:
    version: 1.0.0
    HTML5Runtime_enabled: true
html5_apps_deployer:
  cloudService: sap.fe.cap.sflight
  backendDestinations:
    sflight-srv:
      service: srv
  image:
    # >>> Replace <your-container-registry> with your container registry
    repository: <your-container-registry>/sflight-html5-deployer
    tag: latest
  bindings:
    xsuaa:
      serviceInstanceName: xsuaa
    destination:
      serviceInstanceName: destination
    html5_apps_repo:
      serviceInstanceName: html5-apps-repo-host
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
html5_apps_repo_host:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-host
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: sflight
  config: xs-security.json
srv:
  bindings:
    auth:
      serviceInstanceName: xsuaa
    db:
      fromSecret: sflight-db
  image:
    # >>> Replace <your-container-registry> with your container registry
    repository: <your-container-registry>/sflight-srv
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 1G
    requests:
      ephemeral-storage: 1G
      cpu: 1000m
      memory: 1G
  health_check:
    liveness:
      path: /
    readiness:
      path: /
  env:
    SPRING_PROFILES_ACTIVE: cloud
